"""komandus v2 production release foundations

Revision ID: 20260605_0001
Revises:
Create Date: 2026-06-05
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260605_0001"
down_revision = None
branch_labels = None
depends_on = None

uuid_type = postgresql.UUID(as_uuid=True)

def upgrade() -> None:
    op.create_table("organizations", sa.Column("id", uuid_type, primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("slug", sa.String(128), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_organizations_slug", "organizations", ["slug"], unique=True)
    op.create_table("users", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.String(512), nullable=False), sa.Column("full_name", sa.String(255)), sa.Column("role", sa.String(32), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("refresh_token_hash", sa.String(128)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("employees", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("user_id", uuid_type, sa.ForeignKey("users.id")), sa.Column("full_name", sa.String(255), nullable=False), sa.Column("email", sa.String(320)), sa.Column("role", sa.String(32), nullable=False), sa.Column("telegram_id", sa.BigInteger()), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_employees_organization_id", "employees", ["organization_id"])
    op.create_index("ix_employees_telegram_id", "employees", ["telegram_id"])
    op.create_table("telegram_account_links", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("employee_id", uuid_type, sa.ForeignKey("employees.id"), nullable=False), sa.Column("telegram_id", sa.BigInteger(), nullable=False), sa.Column("telegram_username", sa.String(255)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("organization_id", "telegram_id", name="uq_org_telegram_id"))
    op.create_table("board_integrations", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("encrypted_api_token", sa.Text(), nullable=False), sa.Column("external_project_id", sa.String(255)), sa.Column("external_board_id", sa.String(255)), sa.Column("webhook_secret_hash", sa.String(128)), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("metadata_json", sa.JSON()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("column_mappings", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("board_integration_id", uuid_type, sa.ForeignKey("board_integrations.id"), nullable=False), sa.Column("task_status", sa.String(32), nullable=False), sa.Column("external_column_id", sa.String(255), nullable=False), sa.Column("external_column_name", sa.String(255)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("board_integration_id", "task_status", name="uq_board_status_mapping"))
    op.create_table("employee_board_mappings", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("board_integration_id", uuid_type, sa.ForeignKey("board_integrations.id"), nullable=False), sa.Column("employee_id", uuid_type, sa.ForeignKey("employees.id"), nullable=False), sa.Column("external_user_id", sa.String(255), nullable=False), sa.Column("external_email", sa.String(320)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("board_integration_id", "employee_id", name="uq_employee_board_mapping"))
    op.create_table("komandus_tasks", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("employee_id", uuid_type, sa.ForeignKey("employees.id")), sa.Column("title", sa.String(500), nullable=False), sa.Column("description", sa.Text()), sa.Column("status", sa.String(32), nullable=False), sa.Column("due_at", sa.DateTime()), sa.Column("source_chat_id", sa.BigInteger()), sa.Column("source_message_id", sa.BigInteger()), sa.Column("llm_confidence", sa.Float()), sa.Column("llm_model", sa.String(128)), sa.Column("extraction_version", sa.String(64)), sa.Column("external_task_id", sa.String(255)), sa.Column("external_task_url", sa.String(1024)), sa.Column("accepted_at", sa.DateTime()), sa.Column("completed_at", sa.DateTime()), sa.Column("rejected_at", sa.DateTime()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_komandus_tasks_external_task_id", "komandus_tasks", ["external_task_id"])
    op.create_table("task_confirmations", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("task_id", uuid_type, sa.ForeignKey("komandus_tasks.id"), nullable=False), sa.Column("employee_id", uuid_type, sa.ForeignKey("employees.id")), sa.Column("status", sa.String(32), nullable=False), sa.Column("decline_reason", sa.Text()), sa.Column("responded_at", sa.DateTime()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("audit_logs", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id")), sa.Column("user_id", uuid_type, sa.ForeignKey("users.id")), sa.Column("action", sa.String(64), nullable=False), sa.Column("entity_type", sa.String(64)), sa.Column("entity_id", sa.String(64)), sa.Column("metadata_json", sa.JSON()), sa.Column("request_id", sa.String(64)), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("processed_webhook_events", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("event_id", sa.String(255), nullable=False), sa.Column("payload_hash", sa.String(128), nullable=False), sa.Column("processed_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("provider", "event_id", name="uq_provider_event"))
    op.create_table("analytics_snapshots", sa.Column("id", uuid_type, primary_key=True), sa.Column("organization_id", uuid_type, sa.ForeignKey("organizations.id"), nullable=False), sa.Column("snapshot_date", sa.DateTime(), nullable=False), sa.Column("kind", sa.String(64), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("organization_id", "snapshot_date", "kind", name="uq_snapshot_kind_date"))

def downgrade() -> None:
    for table in ["analytics_snapshots", "processed_webhook_events", "audit_logs", "task_confirmations", "komandus_tasks", "employee_board_mappings", "column_mappings", "board_integrations", "telegram_account_links", "employees", "users", "organizations"]:
        op.drop_table(table)
